require(ggplot2)
data <- read.csv("./result.txt")
data$count2 <- as.numeric(as.character(data[,2]))
data$instruction2 <- as.numeric(as.character(data[,1]))
data <- na.omit(data)
data <- subset(data, count2 < 1000000)
p <- ggplot(data, aes(x = instruction2/1000000, y = count2)) + geom_point(size = 0.1, alpha = 0.1) + ylim(0, max(data$count2, na.rm = TRUE))
p1 <- p + stat_density_2d(aes(fill = log(..level..)), geom = "polygon") + scale_fill_gradientn(colours = rev(rainbow(10, end = 4/6)))
ggsave(p, filename="result.pdf", width = 16, height = 9)
