require(ggplot2)
args = commandArgs(trailingOnly = TRUE)
data <- read.csv(paste(args, ".txt", sep = ""))
data$count2 <- as.numeric(as.character(data[,2]))
data$instruction2 <- as.numeric(as.character(data[,1]))
data <- na.omit(data)
data <- subset(data, count2 < 1000000)
p <- ggplot(data, aes(x = instruction2/1000000, y = count2)) + geom_point(size = 0.1, alpha = 0.1) + ylim(0, max(data$count2, na.rm = TRUE))
ggsave(p, filename=paste(args, ".pdf", sep = ""), width = 16, height = 9)
