#!/bin/bash

echo "making..."
make
make -C simpletest
echo "rming..."
rm -f err-* out-* res-*
echo "pythoning..."
python data-collection.py -e MEM_LOAD_RETIRED.L3_MISS -e MEM_LOAD_RETIRED.L3_HIT -i simpletest/thousand.in simpletest/matrixmultiplier